#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="esp32c3"
BAUD="${BAUD:-460800}"
PORT="${PORT:-}"
MONITOR=0
ONION_SHARED_SECRET="${ONION_SHARED_SECRET:-02eb3d5e04fd2dc9cbb6f3f5c6c9d89d9c96acd987cc24ddf9f717f9480e8786}"
BEACON_WIFI_SSID="${BEACON_WIFI_SSID:-CIC Guest}"
BEACON_WIFI_PASSWORD="${BEACON_WIFI_PASSWORD:-1nnovation}"
BEACON_SERVER_URL="${BEACON_SERVER_URL:-https://oniondao.dev/api/badge/checkin}"
BEACON_SERVER_CA_PEM="${BEACON_SERVER_CA_PEM:-}"
BEACON_SHARED_SECRET="${BEACON_SHARED_SECRET:-${BADGE_API_KEY:-$ONION_SHARED_SECRET}}"
BEACON_ID="${BEACON_ID:-beacon-c3-001}"
BEACON_ROOM="${BEACON_ROOM:-front-desk}"
BEACON_LABEL="${BEACON_LABEL:-Front Desk Check In}"
BEACON_ESPNOW_CHANNEL="${BEACON_ESPNOW_CHANNEL:-6}"
BEACON_RSSI_THRESHOLD_DBM="${BEACON_RSSI_THRESHOLD_DBM:--50}"
BEACON_ADVERTISE_INTERVAL_MS="${BEACON_ADVERTISE_INTERVAL_MS:-1000}"
BEACON_DEFAULT_POINTS="${BEACON_DEFAULT_POINTS:-0}"
BEACON_ESPNOW_PMK="${BEACON_ESPNOW_PMK:-onion-checkin-01}"

usage() {
  cat <<'EOF'
Usage: scripts/build-flash.sh [options]

Build and flash the ESP32-C3 check-in beacon firmware.
This performs an app update only. It does not erase flash.

Options:
  -p, --port PORT    Flash a specific serial port instead of auto-detecting
  -b, --baud BAUD    Flash baud rate (default: 460800, or $BAUD)
  --monitor          Open idf.py monitor after flashing
  -h, --help         Show this help

Environment:
  IDF_EXPORT=/path/to/export.sh  ESP-IDF export script to source
  PORT=/dev/cu.usbserial-10      Same as --port
  BAUD=921600                    Same as --baud
  BEACON_WIFI_SSID="CIC Guest"   Baked WiFi SSID
  BEACON_WIFI_PASSWORD=1nnovation Baked WiFi password
  BADGE_API_KEY=...              Baked beacon bearer secret
  ONION_SHARED_SECRET=...        Default for BADGE_API_KEY
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -p|--port)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 2; }
      PORT="$2"
      shift 2
      ;;
    -b|--baud)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 2; }
      BAUD="$2"
      shift 2
      ;;
    --erase)
      echo "This helper does not erase flash." >&2
      echo "Use idf.py erase-flash manually only when you intentionally want to clear beacon state." >&2
      exit 2
      ;;
    --monitor)
      MONITOR=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    echo "Install ESP-IDF or pass IDF_EXPORT=/path/to/esp-idf/export.sh" >&2
    exit 1
  fi
}

source_esp_idf() {
  command -v idf.py >/dev/null 2>&1 && return 0

  local candidates=()
  if [[ -n "${IDF_EXPORT:-}" ]]; then
    candidates+=("$IDF_EXPORT")
  fi

  candidates+=(
    "$HOME/.espressif/v5.5.4/esp-idf/export.sh"
    "$HOME/.espressif-5.5.4/v5.5.4/esp-idf/export.sh"
    "$HOME/esp/esp-idf/export.sh"
    "$HOME"/.espressif/v5.5.*/esp-idf/export.sh
    "$HOME"/.espressif-5.5.*/v5.5.*/esp-idf/export.sh
    "$HOME/.platformio/packages/framework-espidf/export.sh"
  )

  local export_script
  local export_log="${TMPDIR:-/tmp}/check-in-beacon-c3-idf-export.log"
  for export_script in "${candidates[@]}"; do
    if [[ -f "$export_script" ]]; then
      echo "Loading ESP-IDF from $export_script"
      # shellcheck disable=SC1090
      if . "$export_script" >"$export_log" 2>&1; then
        command -v idf.py >/dev/null 2>&1 && return 0
      else
        echo "Failed to load ESP-IDF from $export_script" >&2
        tail -n 40 "$export_log" >&2 || true
      fi
    fi
  done

  return 1
}

esptool_command() {
  if command -v esptool.py >/dev/null 2>&1; then
    echo "esptool.py"
  elif command -v esptool >/dev/null 2>&1; then
    echo "esptool"
  else
    echo ""
  fi
}

c_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

write_generated_config() {
  local config_path="$PROJECT_DIR/main/beacon_config.generated.h"

  {
    printf '#pragma once\n\n'
    printf '// Generated by scripts/build-flash.sh. Do not commit.\n\n'
    printf '#define BEACON_WIFI_SSID %s\n' "$(c_string "$BEACON_WIFI_SSID")"
    printf '#define BEACON_WIFI_PASSWORD %s\n' "$(c_string "$BEACON_WIFI_PASSWORD")"
    printf '#define BEACON_SERVER_URL %s\n' "$(c_string "$BEACON_SERVER_URL")"
    printf '#define BEACON_SERVER_CA_PEM %s\n' "$(c_string "$BEACON_SERVER_CA_PEM")"
    printf '#define BEACON_SHARED_SECRET %s\n' "$(c_string "$BEACON_SHARED_SECRET")"
    printf '#define BEACON_ID %s\n' "$(c_string "$BEACON_ID")"
    printf '#define BEACON_ROOM %s\n' "$(c_string "$BEACON_ROOM")"
    printf '#define BEACON_LABEL %s\n' "$(c_string "$BEACON_LABEL")"
    printf '#define BEACON_ESPNOW_CHANNEL %s\n' "$BEACON_ESPNOW_CHANNEL"
    printf '#define BEACON_RSSI_THRESHOLD_DBM %s\n' "$BEACON_RSSI_THRESHOLD_DBM"
    printf '#define BEACON_ADVERTISE_INTERVAL_MS %s\n' "$BEACON_ADVERTISE_INTERVAL_MS"
    printf '#define BEACON_DEFAULT_POINTS %s\n' "$BEACON_DEFAULT_POINTS"
    printf '#define BEACON_ESPNOW_PMK %s\n' "$(c_string "$BEACON_ESPNOW_PMK")"
  } >"$config_path"

  echo "Wrote script-managed config: main/beacon_config.generated.h"
}

candidate_ports() {
  local patterns=(
    "/dev/cu.usbserial"* "/dev/tty.usbserial"*
    "/dev/cu.usbmodem"* "/dev/tty.usbmodem"*
    "/dev/cu.wchusbserial"* "/dev/tty.wchusbserial"*
    "/dev/cu.SLAB_USBtoUART"* "/dev/tty.SLAB_USBtoUART"*
    "/dev/ttyUSB"* "/dev/ttyACM"*
  )
  local port
  for port in "${patterns[@]}"; do
    [[ -e "$port" ]] && printf '%s\n' "$port"
  done | sort -u
}

probe_esp32c3_port() {
  local port="$1"
  local output

  if ! output="$("$ESPTOOL" --chip auto --port "$port" chip_id 2>&1)"; then
    return 1
  fi

  grep -Eiq 'ESP32-C3|ESP32C3|esp32c3' <<<"$output"
}

detect_port() {
  local port
  while IFS= read -r port; do
    echo "Probing $port..." >&2
    if probe_esp32c3_port "$port"; then
      printf '%s\n' "$port"
      return 0
    fi
  done < <(candidate_ports)

  return 1
}

source_esp_idf || true
require_command idf.py
ESPTOOL="$(esptool_command)"
if [[ -z "$ESPTOOL" ]]; then
  echo "Required command not found: esptool.py or esptool" >&2
  echo "Install ESP-IDF or pass IDF_EXPORT=/path/to/esp-idf/export.sh" >&2
  exit 1
fi

cd "$PROJECT_DIR"
write_generated_config

if [[ -z "$PORT" ]]; then
  echo "Searching for the first available ESP32-C3 serial board..."
  if ! PORT="$(detect_port)"; then
    echo "No ESP32-C3 board found on common serial ports." >&2
    echo "Connect the beacon, or pass a port explicitly with --port /dev/..." >&2
    exit 1
  fi
else
  if [[ ! -e "$PORT" ]]; then
    echo "Serial port does not exist: $PORT" >&2
    exit 1
  fi
  if ! probe_esp32c3_port "$PORT"; then
    echo "Port exists but did not respond as an ESP32-C3: $PORT" >&2
    exit 1
  fi
fi

echo "Using ESP32-C3 on $PORT"

if [[ ! -f sdkconfig ]] || ! grep -q '^CONFIG_IDF_TARGET="esp32c3"$' sdkconfig; then
  idf.py set-target "$TARGET"
fi

idf.py build

if [[ "$MONITOR" -eq 1 ]]; then
  idf.py -p "$PORT" -b "$BAUD" flash monitor
else
  idf.py -p "$PORT" -b "$BAUD" flash
fi
